services:
  mongodb:
    image: mongo:latest
    container_name: votacao_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: votacao_user
      MONGO_INITDB_ROOT_PASSWORD: votacao_password
      MONGO_INITDB_DATABASE: votacao_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/votacao_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: votacao_app
    ports:
      - "8080:8080"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: votacao_db
      MONGODB_USERNAME: votacao_user
      MONGODB_PASSWORD: votacao_password
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

  influxdb:
    image: influxdb:1.8
    container_name: votacao_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: votacao_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

  k6:
    image: grafana/k6:latest
    container_name: votacao_k6
    volumes:
      - ./k6:/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - influxdb
      - app

volumes:
  mongodb_data:
  influxdb_data:
  grafana_data: